### ISSUE TITLE
Stack setup fails on Alpine without GNU tar

### ISSUE THREAD

**Issue by kfigiela** [mitchty/alpine-linux-ghc-bootstrap#11]
It's not necessarily a bug, however I think it's worth sharing here…

I'm trying to install ghcjs on the image using `stack setup` – it fails, as stack requires GNU tar (corresponding issue https://github.com/commercialhaskell/stack/issues/2146). The workaround for now is to install GNU tar (`apk add tar`) and the build will start.

**Comment by mitchty** [comment]
Yeah I'd consider this a bug in stack most likely, at the least it should test tar to see if its gnu tar.

Realistically this would happen on any busy box distribution, of which I think alpine linux is probably one of the most used at this point due to docker.

A caveat, I have no idea how well stack setup will work on alpine linux, the images it pulls down are the bindists that use gnu libc.

**Comment by kfigiela** [comment]
I intend to install ghcjs, so libc issue should not be a problem (ghcjs is built using already installed GHC). I will let you know as soon as I get it running (or fail)

**Comment by mitchty** [comment]
Sounds good, i've never used ghcjs so you're blazing a new trail at the least. My use of stack tends to be more for building executables than anything else. Good luck!

**Comment by kfigiela** [comment]
Good news! It builds fine with the instructions from http://docs.haskellstack.org/en/stable/ghcjs/
Probably I will install ghcjs without `stack setup` (that means: possible to make apk package), so if I find some time I will make PR with this stuff.

**Comment by mitchty** [comment]
Going to close this issue out given everything is working which admittedly i'm surprised at but I've never used ghcjs so maybe I shouldn't be surprised. Thanks for the information @kfigiela !
