### ISSUE TITLE
aws S3 repository does not exist for ghc8.0

### ISSUE THREAD

**Issue by erebe** [mitchty/alpine-linux-ghc-bootstrap#12]
Hello,

When using the ghc 8 image and doing apk update && apk upgrade.
It complains that APKINDEX.tar.gz does not exist at the path
"https://s3-us-west-2.amazonaws.com/alpine-ghc/next/8.0/"

Is the image outdated ?

**Comment by PierreR** [comment]
I have the same problem.

;-)

**Comment by mitchty** [comment]
My bad, it exists but wasn't signed properly.

That should be fixed now if you do an apk update. But I'd switch that from alpine-gcc/next/8.0 to just alpine-ghc/8.0, the former is more likely to be broken by me testing things. Just a note for arm, that signed bad too so I'll fix that shortly, but not sure anyone but me is using that at this time.

The docker images should be updating now too. As a note latest is now 8.0.1 and there should be a new image with :7.10 tag for the older stuff. I'll get stack building in 7.10 as well again but 7.10 is somewhat not all that interesting anymore and its summer so I'd rather be out running.

**Comment by erebe** [comment]
I confirm that's working now, Thanks a lot :)

Beside that, would you be interested to write a step by step of how you build those images ?
I tried to use the makefile in the repo, but failed to build ghc 8.0.1 (cannot find the "gtar" command for example)

**Comment by mitchty** [comment]
Good to hear.

I can but its not all that intuitive and I was hoping to rewrite it all once it got upstreamed into alpine linux (if? have to pester them again to see if the 8.0.1 is ok or not, I have a setup to build ghc from git in place but its not all that tested). To be honest I'd rather work towards getting more of this upstream than keep this entire repo/port/hack around but I had bad timing with 8.0 patches as alpine linux 3.4 was coming out so everyone was busy.

So in short it should amount to this (mostly automated but I've been lazy and a bit of it needs to get cleaned up since 8.0):
- cd 8.0/ghc-bootstrap && make -j2

That builds the cross compilers for x86_64 and arm and dumps them into the pwd. Have to put those somewhere on a network accessible location, if you look at the apkbuild for ghc basically the source line for the bootstraps are originating from this stuff. Also note, the arm build takes about 10x as long to complete as the x86_64 build so that is primarily why both are separate docker builds. Technically I could merge both together but I don't see much point this is really a one time deal generally.
- cd .. && make all sign

That should then get you a directory named apks that will build everything in the right order with docker extracting each apk out of the build individually. That is done more to allow you do say do make cabal instead of rebuilding everything which my pre 8.0 stuff was. Note for signing to work, you'll need to have some apk signing keys, obviously I don't publish them here but they're needed sign things.

So the contents of the alpine-keys.tar file is this:

```
$ tar tvf alpine-keys.tar                                   
drwxr-xr-x  0 root   root        0 Jun 22  2015 ./                        
-rw-rw----  0 root   root     1679 Jun 22  2015 ./mitch.tishmack@gmail.com-55881c97.rsa
-rw-r--r--  0 root   root      451 Jun 22  2015 ./mitch.tishmack@gmail.com-55881c97.rsa.pub
-rw-r--r--  0 root   root       71 Jun 22  2015 ./abuild.conf  
```

That is to make sure that abuild uses my signing keys right for the final signing. In between I just use a randomly generated setup so it doesn't matter. Then I just sign everything by copying the files in and signing and copying them back out with the signed keys. (this could be improved tbh)

Then I just rsync the directories up or in s3's case s3cmd sync things around and test/rebuild docker images. For arm however I have to kick things off on an arm builder so that bit is mostly manual, I suppose I should rewrite most of this in say ansible or whatever but its a fairly low priority.

Broken parts of the top level makefile (at the moment almost everything there is broken):
- anything 7.10 related, I was splitting things out to be more like the 8.0 setup but haven't cleaned it up
- most of the syncing is still referring to the old stuff

**Comment by erebe** [comment]
Thank you for the sum-up, I will give it a try when I have some spare time.

Anyway, I want to thank you again for the hard work and for getting it upstream.
What you have done is of great use to me :)
