### ISSUE TITLE
compilation is broken by '-nopie'

### ISSUE THREAD

**Issue by bjin** [mitchty/alpine-linux-ghc-bootstrap#19]
I tried to compile a hello world program with latest `mitchty/alpine-ghc` docker image (and `libc-dev` package installed for `math.h`), and encountered the following error.

    <no location info>: error:
        Warning: Couldn't figure out linker information!
                 Make sure you're using GNU ld, GNU gold or the built in OS X linker, etc.
    gcc: error: unrecognized command line option '-nopie'; did you mean '-no-pie'?
    gcc: error: unrecognized command line option '-nopie'; did you mean '-no-pie'?
    `gcc' failed in phase `Linker'. (Exit code: 1)

**Comment by apriori** [comment]
Check the ghc settings in /usr/ghc-8.0.2 and fix the typo there till the package is fixed.

**Comment by apriori** [comment]
Ohm,  /usr/lib/ghc-8.0.2 I meant

**Comment by mitchty** [comment]
ah yep hold off on that for a bit, I have a fix (bootstrapping with 8.0.2 has made this easier)

This is mostly due to the alpine linux 3.4 hacks not working at all with the 6.21 gcc and alpine linux 3.5.

I'm waiting for arm to finish building but... actually I'll go push up the apks for x86_64, this works there.

**Comment by mitchty** [comment]
Should be fixed, example that would have failed prior:
```
$ docker run -it mitchty/alpine-ghc: latest sh
/ # apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
fetch https://s3-us-west-2.amazonaws.com/alpine-ghc/8.0/x86_64/APKINDEX.tar.gz
v3.5.0-49-g548d5f059f [http://dl-cdn.alpinelinux.org/alpine/v3.5/main]
v3.5.0-48-g8042937a2f [http://dl-cdn.alpinelinux.org/alpine/v3.5/community]
OK: 7972 distinct packages available
/ # apk add ghc alpine-sdk > /dev/null 2>&1
/ # echo 'main = putStrLn "ok"' > /tmp/test.hs
/ # ghc --make /tmp/test.hs
[1 of 1] Compiling Main             ( /tmp/test.hs, /tmp/test.o )
Linking /tmp/test ...
/ # ldd /tmp/test
        /lib/ld-musl-x86_64.so.1 (0x557509e66000)
        libgmp.so.10 => /usr/lib/libgmp.so.10 (0x7f42e8eae000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x557509e66000)
```

Sorry about that getting pushed up without me validating a bit better, I hadn't realized I tested with 3.4 and the latest alpine release was 3.5 until it was late last night.

I've added a ghc --make step to my docker build files to catch this as its an easy way to make sure I don't miss something. But this version is the first version "without pic/pie hacks" at all so shouldn't have any of this weirdness I hope. This is basically the version I *really* want to get upstreamed to alpine linux. I'll finish polishing these updates and pursue that later.

If you can give it a go and validate this version works then I'll close this out. But because it builds cabal/stack/idris as an example it mostly seems to be a functional compiler (pun intended).

**Comment by bjin** [comment]
Yes, I can verify that it works fine now. Thanks!
